#!/bin/bash

make re

function test()
{
    LD_PRELOAD=./libmy_malloc.so $1 &> /dev/null

    if [[ $? == 0 ]]; then
        echo -e "Test: [\e[1;95m$1\e[0m] == \e[1;32mOK\e[0m"
    else
        echo -e "Test: [\e[1;95m$1\e[0m] == \e[1;91;5mKO\e[0m"
    fi
}

test "ls"
test "ls -l"
test "ls -R"
test "ls -a"
test "ls -la"
test "ls -R /"
test "echo -e \"1+1\" | bc"
test "firefox"
test "vlc"
